baseurl = "http://example.org"
title = "Emrys Scott-Murrell"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->Write code | Enjoy life<!--]-->'
  logo = "fa-terminal"
  copyright = "Emrys Scott-Murrell, 2019"

# [[params.social]]
#   medium = "twitter"
#   icon = "twitter"
#   link = "#"

# [[params.social]]
#   medium = "facebook"
#   icon = "facebook"
#   link = "#"

# [[params.social]]
#   medium = "instagram"
#   icon = "instagram"
#   link = "#"

[[params.social]]
  medium = "gmail"
  icon = "envelope"
  link = "mailto:emrys.sm@gmail.com"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin-square"
  link = "https://www.linkedin.com/in/emrysscottmurrell/"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://www.github.com/EmrysSM"

[languages]
[languages.en]
languageName = "English"
weight = 1

# [languages.de]
# languageName = "Deutsch"
# weight = 2
# title = "Dimension"
# description = '<!--[-->this is text, and it cannot contain a new line.<!--]-->'
